<a href="https://colab.research.google.com/github/sarveshmahendramaurya/Numpy/blob/main/NumPy_ufunc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy ufuncs
ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.
ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.
They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.
ufuncs also take additional arguments, like:

$where$ boolean array or condition defining where the operations should take place.

$dtype$ defining the return type of elements.

$out$ output array where the return value should be copied.

##Vectorization
Converting iterative statements into a vector based operation is called vectorization.
It is faster as modern CPUs are optimized for such operations

For example:

Add the Elements of Two Lists

list 1: [1, 2, 3, 4]

list 2: [4, 5, 6, 7]

One way of doing it is to iterate over both of the lists and then sum each elements.

In [ ]:
a=[1, 2, 3, 4]
b=[4, 5, 6, 7]
c=[]
for i,j in zip(a,b):
  d=i+j
  c.append(d)
print(c)


[5, 7, 9, 11]


In [ ]:
#With ufunc, we can use the add() function:
import numpy as np
x=[1,2,3,4]
y=[4,5,6,7]
z=np.add(x,y)
print(z)

[ 5  7  9 11]


#Create Your Own ufunc
To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

function - the name of the function.

inputs - the number of input arguments (arrays).

outputs - the number of output arrays.

In [ ]:
import numpy as np

def myufuncMult(a,b):
  return a*b

myufuncMult=np.frompyfunc(myufuncMult,2,1)
''' here myufuncMult is oour function and
 2 number of input and 1 is number of output'''


Arraya=np.array([1,3,5,7,9])
Arrayb=np.array([11,13,15,17,19])

print(myufuncMult(Arraya,Arrayb),"\n")
print("type of myufuncMult function is ",type(myufuncMult))

[11 39 75 119 171] 

type of myufuncMult function is  <class 'numpy.ufunc'>


Check if a Function is a ufunc
Check the type of a function to check if it is a ufunc or not.
A ufunc should return <class 'numpy.ufunc'>.

In [ ]:
import numpy as np

print(type(np.add))

<class 'numpy.ufunc'>


#Simple Arithmetic Ufunc

You could use arithmetic operators + - * / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.


##Adition
 add() function sums the content of two arrays, and return the results in a new array.

In [1]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.add(Array1,Array2)
print(Array)

[ 8 10 12 14 16 18]


##Subtraction
The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.

In [3]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.subtract(Array2,Array1)
print(Array)

[6 6 6 6 6 6]


##Multiplication
The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

In [5]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.multiply(Array2,Array1)
print(Array)

[ 7 16 27 40 55 72]


##Division
The divide() function divides the values from one array with the values from another array, and return the results in a new array.

In [6]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.divide(Array2,Array1)
print(Array)

[7.  4.  3.  2.5 2.2 2. ]


##Power
The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

In [7]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.power(Array2,Array1)
print(Array)

[      7      64     729   10000  161051 2985984]


##Remainder
Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

In [10]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.remainder(Array2,Array1)
array=np.mod(Array2,Array1)
print(Array)
print(array)


[0 0 0 2 1 0]
[0 0 0 2 1 0]


##Quotient and Mod
The divmod() function return both the quotient and the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [11]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.divmod(Array2,Array1)
print(Array)

(array([7, 4, 3, 2, 2, 2]), array([0, 0, 0, 2, 1, 0]))


##Absolute Values
Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

In [15]:
import numpy as np

Array2=np.array([7,8,-9,10,-11,12])

Array=np.absolute(Array2,Array1)
print(Array)

[ 7  8  9 10 11 12]


#Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

◇truncation

◇fix

◇rounding

◇floor

◇ceil


##Truncation
Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

In [16]:
import numpy as np

Array=np.array([3.686786,2.242345,1.35668,-4.98983740])

Truncation_array=np.trunc(Array)
print(Truncation_array)

[ 3.  2.  1. -4.]


In [17]:
import numpy as np

Array=np.array([3.686786,2.242345,1.35668,-4.98983740])

Truncation_array=np.fix(Array)
print(Truncation_array)

[ 3.  2.  1. -4.]


##Rounding
The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.
E.g. round off to 1 decimal point, 3.16666 is 3.2

In [22]:
import numpy as np

Array=np.array([3.686786,2.242345,1.35668,-4.98983740,1.169067])

round_array=np.around(Array,3)
print(round_array)

[ 3.687  2.242  1.357 -4.99   1.169]


##Floor
The floor() function rounds off decimal to nearest lower integer.
E.g. floor of 3.166 is 3.

In [23]:
import numpy as np

Array=np.array([4.46547,5.345657,3.43667])

floor_array=np.floor(Array)
print(floor_array)

[4. 5. 3.]


##Ceil
The ceil() function rounds off decimal to nearest upper integer.
E.g. ceil of 3.166 is 4.

In [24]:
import numpy as np

Array=np.array([4.787458,6.398570,7.230470,2.49066])

ceil_array=np.ceil(Array)
print(ceil_array)

[5. 7. 8. 3.]
