<a href="https://colab.research.google.com/github/sarveshmahendramaurya/Numpy/blob/main/Numpy_Random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Random


##Random Number
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

##Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless it is related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

In this tutorial we will be using pseudo random numbers.



##Random Number
NumPy offers the random module to work with random numbers.

In [3]:
from numpy import random as rd

a=rd.randint(100)
print(a)

81


##Random Float
The random module's rand() method returns a random float between 0 and 1.

In [5]:
from numpy import random as rd

a=rd.rand()
print(a)

0.25564508146940823


##Random Array
In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.


###Integers
The randint() method takes a size parameter where you can specify the shape of an array.

In [6]:
#Generate a 1-D array containing 5 random integers from 0 to 100:
from numpy import random as rd

Array=rd.randint(100,size=(10))
print(Array)

[75 38 24 93 17 89 69 29  0 99]


In [8]:
from numpy import random as rd

Array=rd.randint(100,size=(5,5))
print(Array)

[[14 54 36 90 11]
 [ 7 83 60 67 83]
 [39 57 76 93 64]
 [75  9 99 68 44]
 [91 58 47 55 92]]


###Floats
The rand() method also allows you to specify the shape of the array.

In [11]:
from numpy import random as rd

Array=rd.rand(5)
print(Array)

[0.38647576 0.34436503 0.30581839 0.47982488 0.10870165]


In [12]:
from numpy import random as rd

Array=rd.rand(5,5)
print(Array)

[[0.86638491 0.45058456 0.81459047 0.64331727 0.22736934]
 [0.83336633 0.88693664 0.22391652 0.31160633 0.42701734]
 [0.46546732 0.2042805  0.29999098 0.09557458 0.26939054]
 [0.62345173 0.23744573 0.33100157 0.84554592 0.42706953]
 [0.32841632 0.10419712 0.19516114 0.21343124 0.44934142]]
