<a href="https://colab.research.google.com/github/sarveshmahendramaurya/Numpy/blob/main/NumPy_ufunc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy ufuncs
ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.
ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.
They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.
ufuncs also take additional arguments, like:

$where$ boolean array or condition defining where the operations should take place.

$dtype$ defining the return type of elements.

$out$ output array where the return value should be copied.

##Vectorization
Converting iterative statements into a vector based operation is called vectorization.
It is faster as modern CPUs are optimized for such operations

For example:

Add the Elements of Two Lists

list 1: [1, 2, 3, 4]

list 2: [4, 5, 6, 7]

One way of doing it is to iterate over both of the lists and then sum each elements.

In [ ]:
a=[1, 2, 3, 4]
b=[4, 5, 6, 7]
c=[]
for i,j in zip(a,b):
  d=i+j
  c.append(d)
print(c)


[5, 7, 9, 11]


In [ ]:
#With ufunc, we can use the add() function:
import numpy as np
x=[1,2,3,4]
y=[4,5,6,7]
z=np.add(x,y)
print(z)

[ 5  7  9 11]


---

#Create Your Own ufunc
To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

function - the name of the function.

inputs - the number of input arguments (arrays).

outputs - the number of output arrays.

In [ ]:
import numpy as np

def myufuncMult(a,b):
  return a*b

myufuncMult=np.frompyfunc(myufuncMult,2,1)
''' here myufuncMult is oour function and
 2 number of input and 1 is number of output'''


Arraya=np.array([1,3,5,7,9])
Arrayb=np.array([11,13,15,17,19])

print(myufuncMult(Arraya,Arrayb),"\n")
print("type of myufuncMult function is ",type(myufuncMult))

[11 39 75 119 171] 

type of myufuncMult function is  <class 'numpy.ufunc'>


Check if a Function is a ufunc
Check the type of a function to check if it is a ufunc or not.
A ufunc should return <class 'numpy.ufunc'>.

In [ ]:
import numpy as np

print(type(np.add))

<class 'numpy.ufunc'>


---

#Simple Arithmetic Ufunc

You could use arithmetic operators + - * / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.


##Adition
 add() function sums the content of two arrays, and return the results in a new array.

In [ ]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.add(Array1,Array2)
print(Array)

[ 8 10 12 14 16 18]


##Subtraction
The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.

In [ ]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.subtract(Array2,Array1)
print(Array)

[6 6 6 6 6 6]


##Multiplication
The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

In [ ]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.multiply(Array2,Array1)
print(Array)

[ 7 16 27 40 55 72]


##Division
The divide() function divides the values from one array with the values from another array, and return the results in a new array.

In [ ]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.divide(Array2,Array1)
print(Array)

[7.  4.  3.  2.5 2.2 2. ]


##Power
The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

In [ ]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.power(Array2,Array1)
print(Array)

[      7      64     729   10000  161051 2985984]


##Remainder
Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

In [ ]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.remainder(Array2,Array1)
array=np.mod(Array2,Array1)
print(Array)
print(array)


[0 0 0 2 1 0]
[0 0 0 2 1 0]


##Quotient and Mod
The divmod() function return both the quotient and the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [ ]:
import numpy as np

Array1=np.array([1,2,3,4,5,6])
Array2=np.array([7,8,9,10,11,12])

Array=np.divmod(Array2,Array1)
print(Array)

(array([7, 4, 3, 2, 2, 2]), array([0, 0, 0, 2, 1, 0]))


##Absolute Values
Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

In [ ]:
import numpy as np

Array2=np.array([7,8,-9,10,-11,12])

Array=np.absolute(Array2,Array1)
print(Array)

[ 7  8  9 10 11 12]


---

#Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

◇truncation

◇fix

◇rounding

◇floor

◇ceil


##Truncation
Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

In [ ]:
import numpy as np

Array=np.array([3.686786,2.242345,1.35668,-4.98983740])

Truncation_array=np.trunc(Array)
print(Truncation_array)

[ 3.  2.  1. -4.]


In [ ]:
import numpy as np

Array=np.array([3.686786,2.242345,1.35668,-4.98983740])

Truncation_array=np.fix(Array)
print(Truncation_array)

[ 3.  2.  1. -4.]


##Rounding
The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.
E.g. round off to 1 decimal point, 3.16666 is 3.2

In [ ]:
import numpy as np

Array=np.array([3.686786,2.242345,1.35668,-4.98983740,1.169067])

round_array=np.around(Array,3)
print(round_array)

[ 3.687  2.242  1.357 -4.99   1.169]


##Floor
The floor() function rounds off decimal to nearest lower integer.
E.g. floor of 3.166 is 3.

In [ ]:
import numpy as np

Array=np.array([4.46547,5.345657,3.43667])

floor_array=np.floor(Array)
print(floor_array)

[4. 5. 3.]


##Ceil
The ceil() function rounds off decimal to nearest upper integer.
E.g. ceil of 3.166 is 4.

In [ ]:
import numpy as np

Array=np.array([4.787458,6.398570,7.230470,2.49066])

ceil_array=np.ceil(Array)
print(ceil_array)

[5. 7. 8. 3.]


---

#Logs
Logs
NumPy provides functions to perform log at the base 2, e and 10.
We will also explore how we can take log for any base by creating a custom ufunc.
All of the log functions will place -inf or inf in the elements if the log can not be computed.

##Log at Base 2
Use the log2() function to perform log at the base 2.

In [ ]:
import numpy as np

Array=np.array([1,2,4,8,16,32,64])
log2=np.log2(Array)

print(log2)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
import numpy as np

Array2=np.arange(1,10)
'''The arange(1, 10) function returns an array with integers starting from 1 (included) to 10 (not included).'''
logBase2=np.log2(Array2)

print(logBase2)

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


##Log at Base 10
Use the log10() function to perform log at the base 10.

In [ ]:
import numpy as np

Array=np.array([10,50,100,150,200,250,300])
log10=np.log10(Array)

print(log10)

[1.         1.69897    2.         2.17609126 2.30103    2.39794001
 2.47712125]


##Natural Log, or Log at Base e
Use the log() function to perform log at the base e

In [ ]:
import numpy as np

Array=np.array([2.178,4,8,16,24,54])
loge=np.log(Array)
print(loge)

[0.77840702 1.38629436 2.07944154 2.77258872 3.17805383 3.98898405]


##Log at Any Base
NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter:

In [ ]:
import numpy as np
from math import log

np_log=np.frompyfunc(log,2,1)
print(np_log(9,3))

2.0


In [ ]:
print(np_log(np.array([1,2,3,4,5,6]),2.178))

[0.0 0.8904688148152189 1.4113596795437338 1.7809376296304378
 2.0676045587405087 2.3018284943589524]


---

#Summations
What is the difference between summation and addition?
Addition is done between two arguments whereas summation happens over n elements.

In [ ]:
import numpy as np

arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])

newarray=np.sum([arr1,arr2])
#only one element can be pasted to it(sum())
print(newarray)

30


In [ ]:
import numpy as np

arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])

newarray0=np.sum([arr1,arr2],axis=0)
print("summation along axis=0:",newarray0)

newarray1=np.sum([arr1,arr2],axis=1)
print("\nsummation along axis=1:",newarray1)

summation along axis=0: [ 2  4  6  8 10]

summation along axis=1: [15 15]


##Cummulative Sum
Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

Perfom partial sum with the cumsum() function.

In [ ]:
import numpy as np

Array=np.array([1,2,3,4])
cumulative_sum=np.cumsum(Array)
print(cumulative_sum)

[ 1  3  6 10]


---

#product
To find the product of the elements in an array, use the prod() function.

In [ ]:
import numpy as np

Array=np.array([1,2,3,4,5])
product=np.prod(Array)
print(product)

120


In [ ]:
import numpy as np

Array2=np.array([1,2,3,4,5])
Array3=np.array([6,7,8,9,10])

product=np.prod([Array2,Array3])
print(product)

3628800


In [ ]:
import numpy as np

Array2=np.array([1,2,3,4,5])
Array3=np.array([6,7,8,9,10])

product=np.prod([Array2,Array3],axis=1)
print("product along axis=1",product)

product2=np.prod([Array2,Array3],axis=0)
print("\nproduct along axis=0",product2)

product along axis=1 [  120 30240]

product along axis=0 [ 6 14 24 36 50]


##cumulative product
Cummulative product means taking the product partially.

E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]

Perfom partial sum with the cumprod() function.

In [ ]:
import numpy as np

Array=np.array([1,2,3,4,5,6,7,8,9,10])
print(Array)
cumulative_product=np.cumprod(Array)
print(cumulative_product)

[ 1  2  3  4  5  6  7  8  9 10]
[      1       2       6      24     120     720    5040   40320  362880
 3628800]


----

#Differences
A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.

In [ ]:
import numpy as np

Array=np.array([5,10,15,20,25,30,35,40])
diff=np.diff(Array)
print(diff)

[5 5 5 5 5 5 5]


We can perform this operation repeatedly by giving parameter n.

E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, we will do it once more, with the new result: [1-1, 1-1] = [0, 0]

In [ ]:
import numpy as np

Array=np.array([5,10,15,20,25,30,35,40])
diff2=np.diff(Array,n=2)
print(diff2)


[0 0 0 0 0 0]


In [ ]:
Array2=np.array([4,5,7,2,56,89,145,234,456])
diff22=np.diff(Array2,n=2)
print(diff22)

[  1  -7  59 -21  23  33 133]


---

we can also assign n with more than 2

#LCM (Lowest Common Multiple)
The Lowest Common Multiple is the smallest number that is a common multiple of two numbers.

In [ ]:
import numpy as np

a=5
b=10
print(np.lcm(a,b))

10


##LCM in Arrays
o find the Lowest Common Multiple of all values in an array, you can use the reduce() method.

The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension.

In [ ]:
import numpy as np

a=np.array([2,5,8,4])
lcm=np.lcm.reduce(a)
print(lcm)

40


In [ ]:
import numpy as np

a=np.array([7,8,5])
lcm=np.lcm.reduce(a)
print(lcm)

280


---

#GCD (Greatest Common Divisor)
The GCD (Greatest Common Divisor), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers.

In [ ]:
import numpy as np

Array=np.array([57,46])
gcd=np.gcd.reduce(Array)
print(gcd)

1


In [ ]:
Array2=np.array([50,10])
gcd2=np.gcd.reduce(Array2)
print(gcd2)

10


---

#Trigonometric Functions
NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

In [ ]:
import numpy as np

rdian=np.array([0,np.pi/2,np.pi,np.pi*2/3])
sine=np.sin(rdian)
print(sine)

[0.00000000e+00 1.00000000e+00 1.22464680e-16 8.66025404e-01]


In [ ]:
import numpy as np

rdian=np.array([0,np.pi/2,np.pi,np.pi*2/3])
cosine=np.cos(rdian)
print(cosine)

[ 1.000000e+00  6.123234e-17 -1.000000e+00 -5.000000e-01]


##Convert Degrees Into Radians
By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumPy.

Note: radians values are pi/180 * degree_values.

In [ ]:
import numpy as np

degree=np.array([0,30,45,60,90])
rad=np.deg2rad(degree)
print(rad)


[0.         0.52359878 0.78539816 1.04719755 1.57079633]


##Convert Radians to Degrees


In [ ]:
import numpy as np

rad=np.array([np.pi/2,np.pi,1.5*np.pi,2*np.pi])
degree=np.rad2deg(rad)
print(degree)

[ 90. 180. 270. 360.]


##Finding Angles
Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

In [ ]:
import numpy as np

functions=np.array([1,0,-1])

angle=np.arcsin(functions)
print("angles in rad:",angle)

anlge_deg=np.rad2deg(angle)
print("angles in deg:",anlge_deg)

angles in rad: [ 1.57079633  0.         -1.57079633]
angles in deg: [ 90.   0. -90.]


##Hypotenues
Finding hypotenues using pythagoras theorem in NumPy.

NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

In [ ]:
import numpy as np

base=8
perp=6
hyp=np.hypot(base,perp)
print("hypotenues:",hyp)


hypotenues: 10.0


---

#Hyperbolic Functions
NumPy provides the ufuncs sinh(), cosh() and tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values..

In [ ]:
import numpy as np

rad=np.array([np.pi/2,np.pi,1.5*np.pi,2*np.pi])
hyper_sin=np.sinh(rad)
print(hyper_sin)


[  2.3012989   11.54873936  55.6543976  267.74489404]


##Finding Angles
Finding angles from values of hyperbolic sine, cos, tan. E.g. sinh, cosh and tanh inverse (arcsinh, arccosh, arctanh).

Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given.

In [ ]:
import numpy as np

hyp=np.array([2.3012989, 11.54873936, 55.6543976, 267.74489404])
angles=np.arcsinh(hyp)
print("angles in rad",angles)

in_deg=np.rad2deg(angles)
print("angles in deg",in_deg)


angles in rad [1.57079633 3.14159265 4.71238898 6.28318531]
angles in deg [ 89.99999995 180.00000001 270.         360.        ]


----

#NumPy Set Operations
A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, union and difference operations.

##Create Sets
We can use NumPy's unique() method to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays

In [1]:
import numpy as np

set_Array=np.array([1,1,2,4,3,4,6,8,9,10,1])
set_=np.unique(set_Array)
print(set_)

[ 1  2  3  4  6  8  9 10]


##Union
To find the unique values of two arrays, use the union1d() method.

In [2]:
import numpy as np

Array1=np.array([1,2,3,4,5])
Array2=np.array([4,5,6,7,8])

union=np.union1d(Array1,Array2)
print(union)

[1 2 3 4 5 6 7 8]


##Intersection
To find only the values that are present in both arrays, use the intersect1d() method.

In [3]:
import numpy as np

Array1=np.array([1,2,3,4,5])
Array2=np.array([4,5,6,7,8])

Intersection=np.intersect1d(Array1,Array2)
print(Intersection)

[4 5]


**Note:** the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.

##Difference

To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.

In [6]:
import numpy as np

Array1=np.array([1,2,3,4,5])
Array2=np.array([4,5,6,7,8])

diff1=np.setdiff1d(Array1,Array2)
print("Array1-Array2",diff1)

diff2=np.setdiff1d(Array2,Array1)
print("Array2-Array1",diff2)

Array1-Array2 [1 2 3]
Array2-Array1 [6 7 8]


**Note:** the setdiff1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.

##Symmetric Difference


To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

In [7]:
import numpy as np

Array1=np.array([1,2,3,4,5])
Array2=np.array([4,5,6,7,8])

sym=np.setxor1d(Array1,Array2)
print(sym)

[1 2 3 6 7 8]


**Note:** the setxor1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.