<a href="https://colab.research.google.com/github/sarveshmahendramaurya/Numpy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# numpy Array
In Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
Arrays are very frequently used in data science, where speed and resources are very important.

In [ ]:
#We can create a NumPy ndarray object by using the array() function.
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
#Use a tuple to create a NumPy array:
tuple_array=np.array((1,2,3,4,5,6))
print(tuple_array)

[1 2 3 4 5 6]


#Array dimensions
A dimension in arrays is one level of array depth (nested arrays).
nested array: are arrays that have arrays as their elements.


##0D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [ ]:
import numpy as np
ZeroD_array=np.array(5)
print(ZeroD_array)

5


##1D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays.

In [ ]:
import numpy as np
OneD_array=np.array([1,2,3,4,5,6,7])
print(OneD_array)

[1 2 3 4 5 6 7]


##2D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.
NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [ ]:
import numpy as np
TwoD_array=np.array([
    [1,2,3,4],
     [5,6,7,8],
      [9,10,11,12]
    ])
print(TwoD_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##3D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.
These are often used to represent a 3rd order tensor.

In [ ]:
import numpy as np
ThreeD_array=np.array(
[
[[1,2],[3,4]],
[[5,6],[7,8]],
[[9,10],[11,12]]
]
)
print(ThreeD_array)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


##Check Number of Dimensions
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
import numpy as np
Array=np.array(
[
[[1,2],[3,4]],
[[5,6],[7,8]],
[[9,10],[11,12]]
]
)
print(Array.ndim)

3


##Higher Dimensional Arrays
An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.

In [ ]:
import numpy as np
Arr=np.array([1,2,3,4,5,6,7,8,9,10],ndmin=5)
print(Arr)
print(Arr.ndim)

[[[[[ 1  2  3  4  5  6  7  8  9 10]]]]]
5


#Accessing Array Elements
Array indexing is the same as accessing an array element.
You can access an array element by referring to its index number.
The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[0])

1


In [ ]:
print(arr[0]+arr[1]+arr[2])

6


To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [ ]:
import numpy as np
twoD=np.array([
    [1,2,3],
    [4,5,6]
    ])
print(twoD)
'''first parameter is index of list,
 second parameter is index of nested list
 or can be said first parameter is row and second is column index'''
print(twoD[0,1])

[[1 2 3]
 [4 5 6]]
2



To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.



In [ ]:
import numpy as np
threeD=np.array([
    [[1,1.5],[2,2.5],[3,3.5],[4,4.5]],
    [[5,5.5],[6,6.5],[7,7.5],[8,8.5]],
    [[9,9.5],[10,10.5],[11,11.5],[12,12.5]]
])
print(threeD)
print(threeD[0,1,0])

[[[ 1.   1.5]
  [ 2.   2.5]
  [ 3.   3.5]
  [ 4.   4.5]]

 [[ 5.   5.5]
  [ 6.   6.5]
  [ 7.   7.5]
  [ 8.   8.5]]

 [[ 9.   9.5]
  [10.  10.5]
  [11.  11.5]
  [12.  12.5]]]
2.0


In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


Example Explained

arr[0, 1, 2] prints the value 6.
And this is why:
The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]
The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]
The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6



Use negative indexing to access an array from the end.


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


#NumPy Array Slicing
Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like this: [start:end].
We can also define the step, like this: [start:end:step].
If we don't pass start its considered 0
If we don't pass end its considered length of array in that dimension
If we don't pass step its considered 1.
first index is inclued but last is excluded

In [ ]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(array[3:8])

[4 5 6 7 8]


In [ ]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(array[:8])

[1 2 3 4 5 6 7 8]


In [ ]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(array[3:])

[ 4  5  6  7  8  9 10]


In [ ]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(array[3:8:2])

[4 6 8]


##negative slicing
Use the minus operator to refer to an index from the end:

In [ ]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(array[3:-2])

[4 5 6 7 8]


##Step
Use the step value to determine the step of the slicing:

In [ ]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(array[::2])

[1 3 5 7 9]


In [ ]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(array[1::2])

[ 2  4  6  8 10]


##Slicing 2D Arrays

In [ ]:
import numpy as np
TwoDArray=np.array([
    [1,2,3],
    [4,5,6]
])
print(TwoDArray[1,0:])

[4 5 6]


here index of second element is 1,
to choose element first we have to give it's index number

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:, 3])


[4 9]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:,4])

[ 5 10]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:,2])

[3 8]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,0:3])

[[1 2 3]
 [6 7 8]]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,1:5])

[[ 2  3  4  5]
 [ 7  8  9 10]]


#Numpy Datatype
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

##checking Datatype
The NumPy array object has a property called dtype that returns the data type of the array:

In [ ]:
import numpy as np

Array=np.array([1,2,3,4,5,6,7,8,9,10])
print(Array.dtype)

int64


In [ ]:
import numpy as np

Str_Array=np.array(["sarvesh","mahendra","maurya"])
print(Str_Array.dtype)

<U8


In [ ]:
import numpy as np

Float_Array=np.array([1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9])
print(Float_Array.dtype)

float64


##Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [ ]:
import numpy as np

Array=np.array([1,2,3,4,5],dtype='S')
print(Array)
print(Array.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [ ]:
#creating array with 4 bit intiger
import numpy as np

Array=np.array([1,2,3,4,5,6,7,8,9,10],dtype='i4')
print(Array)
print(Array.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
int32


If a type is given in which elements can't be casted then NumPy will raise a ValueError.

##Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [ ]:
import numpy as np

Array=np.array([1.1,1.2,1.3,1.4,1.5])
int_Array=Array.astype('int')
print(int_Array)

[1 1 1 1 1]


In [ ]:
import numpy as np

Array=np.array([1.1,1.2,1.3,1.4,1.5])
strArray=Array.astype('str')
print(strArray)

['1.1' '1.2' '1.3' '1.4' '1.5']


In [ ]:
import numpy as np

Array=np.array([1.1,1.2,1.3,1.4,1.5])
boolArray=Array.astype('bool')
print(boolArray)

[ True  True  True  True  True]


#NumPy Array Copy vs View

##The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



##copy


In [ ]:
import numpy as np

Original_Array=np.array([2,4,6,8,10,12,14,16,18,20])
copy_Array=Original_Array.copy()
Original_Array[0]=22
print('original Array: ',Original_Array)
print('copied Array: ',copy_Array)

original Array:  [22  4  6  8 10 12 14 16 18 20]
copied Array:  [ 2  4  6  8 10 12 14 16 18 20]


##View

In [ ]:
import numpy as np

Original_Array=np.array([2,4,6,8,10,12,14,16,18,20])
view_Array=Original_Array.view()
Original_Array[0]=22
print('original Array: ',Original_Array)
print('view Array: ',view_Array)

original Array:  [22  4  6  8 10 12 14 16 18 20]
view Array:  [22  4  6  8 10 12 14 16 18 20]


In [ ]:
import numpy as np

Original_Array=np.array([2,4,6,8,10,12,14,16,18,20])
view_Array=Original_Array.view()
view_Array[0]=22
print('original Array: ',Original_Array)
print('view Array: ',view_Array)

original Array:  [22  4  6  8 10 12 14 16 18 20]
view Array:  [22  4  6  8 10 12 14 16 18 20]


##Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [ ]:
import numpy as np

Array=np.array([1,2,3,4,5])

c=Array.copy()
v=Array.view()

print(c.base)
print(v.base)

None
[1 2 3 4 5]


#Shape of Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [ ]:
import numpy as np

Array=np.array([1,2,3,4,5])

print(Array.shape)

(5,)


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(arr.shape)

(2, 4)


The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

#Array Reshaping

##Reshaping arrays
Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
#creating 2D array from 1D array
import numpy as np

Array=np.array([1,2,3,4,5,6,7,8,9,
                10,11,12,13,14,15,16,17,18])
print(Array.shape)
Array=Array.reshape(9,2)
print(Array)

(18,)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]]


In [ ]:
#creating 3D array from 1D array
import numpy as np

Array=np.array([1,2,3,4,5,6,7,8,9,
                10,11,12,13,14,15,16,17,18])
print(Array.shape)
Array=Array.reshape(3,3,2)
print(Array)

(18,)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [ ]:
import numpy as np

Array=np.array([1,2,3,4,5,6,7,8,9,
                10,11,12,13,14,15,16,17,18])
Array=Array.reshape(3,3,2)
print(Array.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


The example above returns the original array, so it is a view.

##Unknown Dimension
You are allowed to have one "unknown" dimension.
Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
import numpy as np

Array=np.array([1,2,3,4,5,6,7,8])
Array=Array.reshape(2,2,-1)
print(Array)

#Note: We can not pass -1 to more than one dimension.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.
We can use reshape(-1) to do this.

In [ ]:
import numpy as np

Array=np.array([
    [1,2,3],
    [4,5,6]
])
Array=Array.reshape(-1)
print(Array)

[1 2 3 4 5 6]


#NumPy Array Iterating
Iterating means going through elements one by one.
As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
import numpy as np

Array=np.array([1,2,3,4,5])
for i in Array:
    print(i)

1
2
3
4
5


##Iterating 2D Arrays
In a 2D array it will go through all the rows.

In [ ]:
import numpy as np

Array=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in Array:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
#iterate all the element we have to use nested loop
for i in Array:
    for j in i:
        print(j,end=",")

1,2,3,4,5,6,7,8,9,

##Iterating 3D Arrays
In a 3D array it will go through all the 2-D arrays.

In [ ]:
import numpy as np

Array=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])

for i in Array:
  for j in i:
    for k in j:
      print(k,end=",")

1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,

##Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [ ]:
import numpy as np

Array=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]]
])

for i in np.nditer(Array):
  print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 

In [ ]:
A=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in np.nditer(A):
  print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

##Iterating with different datatype
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [ ]:
import numpy as np
Array=np.array([1,2,3,4,5,6,7])

for i in np.nditer(Array,flags=['buffered'],op_dtypes=['S']):
  print(i,end="\n")

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')


In [ ]:
import numpy as np

Array=np.array([[
    [2,4,6,8,10],
    [12,14,16,18,20],
    [22,24,26,28,30]
]])

for i in np.nditer(Array[ 0:3 , 0:4]):
  print(i,end=' ')

2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 

In [ ]:
for i in np.nditer(Array[ :: , 0:4:2]):
  print(i,end=' ')

2 4 6 8 10 22 24 26 28 30 

##Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.
Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [ ]:
import numpy as np

Array1=np.array([1,2,3,4,5,6,7,8,9,10])
for idx, i in np.ndenumerate(Array1):
  print(idx,i)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10


In [ ]:
Array2=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])
for idx, i in np.ndenumerate(Array2):
  print(idx,i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10


#Joining Array

Joining means putting contents of two or more arrays in a single array.
In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [ ]:
import numpy as np

Array1=np.array([1,2,3,4,5])
Array2=np.array([6,7,8,9,10])

Array=np.concatenate((Array1,Array2))
print(Array)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
Arr1=np.array([
    [1,2,3,4,5,6]
])

Arr2=np.array([
    [7,8,9,10,11,12]
])

Arr=np.concatenate((Arr1,Arr2),axis=0)
#axis=0 for along the column axis=1 for along the row
print("using axis=0\n")
print(Arr,"\n")

Arr=np.concatenate((Arr1,Arr2),axis=1)
#axis=0 for along the column axis=1 for along the row
print("using axis=1\n")
print(Arr)

using axis=0

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

using axis=1

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


##Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [ ]:
import numpy as np

Array1=np.array([1,2,3,4,5])
Array2=np.array([6,7,8,9,10])

Array=np.stack((Array1,Array2),axis=0)
print("Axis=0\n",Array)

print("\n")

Array=np.stack((Array1,Array2),axis=1)
print("Axis=1\n",Array)

Axis=0
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Axis=1
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


##Stacking along the row

In [ ]:
import numpy as np

Array1=np.array([1,2,3,4,5])
Array2=np.array([6,7,8,9,10])

Array=np.hstack((Array1,Array2))
print(Array)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
TwoD_Arr1=np.array([
    [1,2,3],[4,5,6]
])
print("First 2D Array: \n",TwoD_Arr1)

TowD_Arr2=np.array([
    [7,8,9],[10,11,12]
])
print("Second 2D Array: \n",TowD_Arr2)
TwoD_Array=np.hstack((TwoD_Arr1,TowD_Arr2))

print("\n stacked along the row\n",TwoD_Array)

First 2D Array: 
 [[1 2 3]
 [4 5 6]]
Second 2D Array: 
 [[ 7  8  9]
 [10 11 12]]

 stacked along the row
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


##Stacking along the column


In [ ]:
import numpy as np

Array1=np.array([1,2,3,4,5])
Array2=np.array([6,7,8,9,10])

Array=np.vstack((Array1,Array2))
print(Array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


##Stacking along the height

In [ ]:
import numpy as np

Array1=np.array([1,2,3,4,5])
Array2=np.array([6,7,8,9,10])

Array=np.dstack((Array1,Array2))
print(Array)

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


In [ ]:
TwoD_Array1=np.array([
    [1,2,3],[4,5,6]
])
print("First 2D Array: \n",TwoD_Array1)

TwoD_Array2=np.array([
    [7,8,9],[10,11,12]
])
print("Second 2D Array: \n",TwoD_Array2,"\n")

TwoD_Array=np.dstack((TwoD_Array1,TwoD_Array2))
print('stacked along the height\n', TwoD_Array)

First 2D Array: 
 [[1 2 3]
 [4 5 6]]
Second 2D Array: 
 [[ 7  8  9]
 [10 11 12]] 

stacked along the height
 [[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


#Splitting Array
Splitting is reverse operation of Joining.
Joining merges multiple arrays into one and Splitting breaks one array into multiple.
We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [ ]:
import numpy as np

Array=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
Array=np.array_split(Array,5)
print(Array)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12]), array([13, 14, 15])]


In [ ]:
TwoD_Array=np.array([
    [1,2,3,4,5],
     [6,7,8,9,10],
      [11,12,13,14,15]
])
TwoD_split=np.array_split(TwoD_Array,3)
print(TwoD_split)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]])]


In [ ]:
TwoD_split2=np.array_split(TwoD_Array ,5)
print(TwoD_split2)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]]), array([], shape=(0, 5), dtype=int64), array([], shape=(0, 5), dtype=int64)]


Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

you can specify which axis you want to do the split around.

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


An alternate solution is using hsplit() opposite of hstack()

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8,9]])

Array1=np.hsplit(arr,3)
print(Array)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12]), array([13, 14, 15])]


In [ ]:
Array2=np.vsplit(arr,3)
print(Array2)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


#Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.
To search an array, use the where() method.

In [ ]:
import numpy as np

Array=np.array([1,2,3,4,5])
print("index of searcthing item: ",np.where(Array==5))

index of searcthing item:  (array([4]),)


In [ ]:
#for multiple same items
Arr=np.array([1,2,4,7,9,2,1,1,1,6,6])
print("index of searcthing items: ",np.where(Arr==1))

index of searcthing items:  (array([0, 6, 7, 8]),)
